### ISSUE TITLE
Question about use sendMediaGroup method

### ISSUE THREAD

**Issue by xartem** [nutgram/docs#32]
Hi, in the documentation I not found how to use the sendMediaGroup method, can anyone tell me how to use it. I'm inserting an array, it doesn't work.
```
                 foreach($post->media as $m) {
                    $media_group[] = fopen(storage_path('app'.$m->path), 'r+');
                }

                $bot->sendMediaGroup($media_group, [
                    'chat_id' => $post->channel->chat_id,
                ]);
```
I look at the code I need InputMediaPhoto[] InputMediaVideo[] but I don't understand how to use it, can anyone give me an example? 

Also is it this method that allows you to attach a media group to a previously created text message? I need to send a text message with multiple videos and photos in one message to a channel.

Thanks

**Comment by xartem** [comment]
![images-and-text](https://github.com/nutgram/docs/assets/13962589/232d560d-6964-4ec6-b2ef-3066c27a0277)
Thanks, I got the group media to send, but without message. Can Nutgram send messages like in the screenshot in the attachment?

**Comment by Lukasss93** [comment]
Just add a caption to the first image

**Comment by xartem** [comment]
Thanks

**Comment by partenit** [comment]
Trying this example as is:
Nutgram 4:
https://github.com/nutgram/nutgram/blob/master/examples/send_album.php
/from_file

Got this error on MacOS 12.6 
GuzzleHttp\Exception\ClientException: Client error: `POST https://api.telegram.org/bot.../sendMediaGroup` resulted in a `400 Bad Request` response:
{"ok":false,"error_code":400,"description":"Bad Request: can't parse InputMedia: media not found"}
 in /Users/admin/Documents/itop_telegram_bot/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

/from_url example working properly
