### ISSUE TITLE
How to display multiselect or checkboxes?

### ISSUE THREAD

**Issue by wahyuief** [nutgram/docs#43]
How does one handle multi-select or checkboxes

Something like this http://www.w3schools.com/html/tryit.asp?filename=tryhtml_checkbox

Thanks in advance

**Comment by sergix44** [comment]
![77f65a7f-7fe3-47ab-943f-d15f968f57e9](https://github.com/nutgram/docs/assets/4172890/19884fcd-7dec-4a16-9de7-edd6768baf42)
